# Generated by Django 4.2.1 on 2024-01-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adusums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_entry', models.DateField()),
                ('name_of_provincials', models.CharField(max_length=255)),
                ('current_community', models.CharField(max_length=255)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='adusums/')),
                ('status', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catalogue_name', models.CharField(max_length=255)),
                ('catalogue_file', models.FileField(blank=True, null=True, upload_to='catalogues/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IgnatianThoughts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_month', models.CharField(max_length=255)),
                ('thought_day', models.CharField(max_length=255)),
                ('thought_item', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('author', models.TextField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopesPrayerIntentions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prayer_month', models.CharField(max_length=255)),
                ('prayer_year', models.CharField(max_length=255)),
                ('prayer_name', models.CharField(max_length=255)),
                ('prayer_item', models.CharField(max_length=255)),
                ('prayer_image', models.ImageField(blank=True, null=True, upload_to='popes-prayer-intentions/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_description', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shukran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shukran_name', models.CharField(max_length=255)),
                ('shukran_year', models.CharField(max_length=255)),
                ('shukran_file', models.FileField(blank=True, null=True, upload_to='shukran/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_day', models.CharField(max_length=255)),
                ('event_month', models.CharField(max_length=255)),
                ('event_year', models.CharField(max_length=255)),
                ('event_month_number', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('event_description', models.CharField(max_length=255)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('event_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sjaorApp.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('document_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sjaorApp.documentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('user_type', models.CharField(default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
