# Generated by Django 4.2.1 on 2024-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adusums',
            old_name='full_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='adusums',
            name='fullname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
