# Generated by Django 4.2.1 on 2024-01-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0002_rename_full_name_adusums_username_adusums_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adusums',
            old_name='email',
            new_name='email_address',
        ),
    ]
