# Generated by Django 4.2.1 on 2024-01-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catalogue_name', models.CharField(max_length=255)),
                ('catalogue_file', models.FileField(blank=True, null=True, upload_to='catalogues/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IgnatianThoughts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thought_month', models.CharField(max_length=255)),
                ('thought_day', models.CharField(max_length=255)),
                ('thought_item', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopesPrayerIntentions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prayer_month', models.CharField(max_length=255)),
                ('prayer_year', models.CharField(max_length=255)),
                ('prayer_name', models.CharField(max_length=255)),
                ('prayer_item', models.CharField(max_length=255)),
                ('prayer_image', models.ImageField(blank=True, null=True, upload_to='popes-prayer-intentions/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_day', models.CharField(max_length=255)),
                ('event_month', models.CharField(max_length=255)),
                ('event_month_number', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('event_description', models.CharField(max_length=255)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('event_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sjaorApp.eventcategory')),
            ],
        ),
    ]
