# Generated by Django 4.2.1 on 2024-02-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0002_necrology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necrology',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='necrologies/'),
        ),
    ]
