# Generated by Django 4.2.1 on 2024-01-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0003_rename_email_adusums_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avm_title', models.CharField(max_length=255)),
                ('avm_body', models.TextField()),
                ('avm_picture', models.ImageField(blank=True, null=True, upload_to='archivum/')),
                ('avm_video', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
