# Generated by Django 4.2.1 on 2024-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0003_catalogues_documents_eventcategory_ignatianthoughts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shukran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shukran_name', models.CharField(max_length=255)),
                ('shukran_year', models.CharField(max_length=255)),
                ('shukran_file', models.FileField(blank=True, null=True, upload_to='shukran/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
