# Generated by Django 4.2.1 on 2024-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0004_archivum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivum',
            name='avm_video',
            field=models.CharField(blank=True, max_length=12255, null=True),
        ),
    ]
