# Generated by Django 4.2.1 on 2024-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0004_shukran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adusums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_entry', models.DateField()),
                ('name_of_provincials', models.CharField(max_length=255)),
                ('current_community', models.CharField(max_length=255)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='adusums/')),
                ('status', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
