# Generated by Django 4.2.1 on 2024-01-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0006_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
