# Generated by Django 4.2.1 on 2024-01-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0007_news_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='document_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sjaorApp.documentcategory'),
        ),
    ]
