# Generated by Django 4.2.1 on 2024-01-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sjaorApp', '0008_documentcategory_documents_document_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ignatianthoughts',
            name='added_on',
        ),
    ]
